/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6/userguide/building_java_projects.html
 */

plugins {
    kotlin("jvm") version "1.8.0"
}
allprojects {
    repositories {
        // Use Maven Central for resolving dependencies.
        mavenCentral()
    }
}



java.sourceCompatibility = JavaVersion.VERSION_17

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
