name: Deploy kafka manager to dev

on:
  push:
    branches:
      - main
    paths:
      - "dab-kafka-manager/dev/*.yaml"
  workflow_dispatch:

jobs:
  deploy-dev:
    permissions:
      id-token: write
      contents: read
    name: Deploy kafka-manager to dev
    uses: ./.github/workflows/deploy-kafka-manager.yaml
    with:
      env: dev
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
