name: pull requests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: publish  -Pversion=${{ github.GITHUB_REF_NAME }}-SNAPSHOT
