name: release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Set release tag
        run: |
          export TAG_NAME="$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M).$(echo $GITHUB_SHA | cut -c 1-12)"
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: -Pversion=${{ env.RELEASE_TAG }} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
